name: MRGE AI Testing  

on: [push, pull_request]  

jobs:
  ai-testing:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code  
        uses: actions/checkout@v3  

      - name: Run MRGE AI Tests  
        run: npx mrge test  
