name: Security Scan & GitHub Issue Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read URLs from file
        id: read_urls
        run: echo "URLS=$(cat urls.txt | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Pull ZAP Docker Image
        run: docker pull zaproxy/zap-stable

      - name: Set proper permissions
        run: chmod -R 777 $(pwd)

      - name: Run ZAP Baseline Scan
        run: |
          for url in $URLS; do
              sanitized_url=$(echo $url | sed 's|https\?://||g' | sed 's|/|_|g' | sed 's|:|_|g' | sed 's|\.\|_|g')
              docker run --rm -v $(pwd):/zap/wrk -t zaproxy/zap-stable zap-baseline.py -t $url -J zap_baseline_report_$url.json
          done

      - name: Run ZAP Full Scan
        run: |
          for url in $URLS; do
            sanitized_url=$(echo $url | sed 's|https\?://||g' | sed 's|/|_|g' | sed 's|:|_|g' | sed 's|\.\|_|g')
            docker run --rm -v $(pwd):/zap/wrk -t zaproxy/zap-stable zap-full-scan.py -t $url -J zap_full_report_$url.json
          done

      - name: Upload Reports as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: "*.json"

  analyze_reports:
    needs: security_scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Reports
        uses: actions/download-artifact@v4
        with:
          name: zap-reports

      - name: Install Python Dependencies
        run: pip install openai requests fuzzywuzzy pandas

      - name: Run AI-powered Analysis and Issue Creation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          GITHUB_BRANCH: ${{ github.ref_name }}
        run: python analyze_and_create_issues.py
